### ISSUE TITLE
Define REST API in BE to be used from FE

### ISSUE THREAD

**Issue by jgoerner** [jgoerner/corona-hackathon#13]
## 📃 Description
> To be able to better understand what an issue is about, one shall provide some further guidance.
This is what the **Description** is about

We need to define the REST API with (i) endpoints and (ii) types early, to start developing the FE stubs (or be able to generate them).

## 🚧 Definition of Ready
> To be able to parallelise the work, one has to ensure, that the issues are atomic and contain all information that are needed. The **Definition of Ready** is a checklist which has to be completed, before the issues should be worked on.

The issue ...

- [x] ... has an expressive title
- [x] ... has a concise description
- [x] ... has a content label (e.g. `infrastructure`, `frontend`, `backend`, ...)
- [x] ... has a difficulty label (e.g. `easy`, `medium`, `hard`, ...)
- [x] ... is linked to the global task board
- [x] ... has a definition of done

## ✅Definition of Done 
> To be able to objectively judge, whether a task is done or not, certain acceptance criteria have to be defined. This is what the **Definition of Done** is about.

- [x] list of required endpoints

**Comment by lschlesinger** [comment]
# Endpoints
- **Authentication/Account Context** {email, password, employee_id, employer_id}
  - `POST /login {email, password} -> bool`
  - `POST /register {email, password} -> bool`
  - `GET /session -> bool`
  - *Account Mgmt*
    - `GET /user -> Account`
    - `PUT /user {old_password, new_password} -> Account`
- **Employee Mgmt**
  - `POST /employee {name, agegroup, location, skills:bool[]} -> Employee`
  - `GET /employee/:id -> Employee` (only if current Account is owner of Employee)
  - `PUT /employee/:id {name, agegroup, location, skills:bool[]} -> Employee` (only if current Account is owner of Employee)
  - `DELETE /employee/:id -> void` (only if current Account is owner of Employee)
- **Employer Mgmt**
  - `POST /employer {name, domain, homepage} -> Employer`
  - `GET /employer/:id -> Employer`(only if current Account is owner of Employer)
  - `PUT /employer/:id {name, domain, homepage} -> Employer` (only if current Account is owner of Employer)
  - _Job Mgmt_ (only if current Account is owner of Employer who owns Job)
    - `POST /job {title, desc, location, qty, salary} -> Job`
    - `GET /job -> [Job]` (**public**)
    - `GET /job/:id -> Job` (**public**)
    - `PUT /job/:id {title, desc, location, qty, salary} -> Job`
    - `DELETE /job/:id -> void`
- **Smart Allocator**
  - `GET /matches -> [Job Recommendation]` (only for employees possible)
- **Contracting**
  - `POST /job/:id/contract {employee_id (from sec.cxt), timestamp, signed, video_verified} -> Contract`
  - `GET /job/:id/contract -> [Contract]` (only employer who owns job)
  - `GET /job/:id/contract/:id -> Contract` (only employer who owns job and employee who got job)
  - `PUT /job/:id/contract/:id {signed, video_verified} -> Contract` (only employer who owns job and employee who got job)
