### ISSUE TITLE
DB Schema Requirements

### ISSUE THREAD

**Issue by jgoerner** [jgoerner/corona-hackathon#18]
## 📃 Description
> To be able to better understand what an issue is about, one shall provide some further guidance.
This is what the **Description** is about

This issue deals with information that should come from the database.

What tables? What columns? What Information?

## 🚧 Definition of Ready
> To be able to parallelise the work, one has to ensure, that the issues are atomic and contain all information that are needed. The **Definition of Ready** is a checklist which has to be completed, before the issues should be worked on.

The issue ...

- [x] ... has an expressive title
- [x] ... has a concise description
- [x] ... has a content label (e.g. `infrastructure`, `frontend`, `backend`, ...)
- [x] ... has a difficulty label (e.g. `easy`, `medium`, `hard`, ...)
- [x] ... is linked to the global task board
- [x] ... has a definition of done

## ✅Definition of Done 
> To be able to objectively judge, whether a task is done or not, certain acceptance criteria have to be defined. This is what the **Definition of Done** is about.

- [x] list of required tables / columns / etc.

**Comment by floro91** [comment]
[200321_SWAG_data_table.xlsx](https://github.com/jgoerner/corona-hackathon/files/4363219/200321_SWAG_data_table.xlsx)

**Comment by floro91** [comment]
| table              | column                   | dtype       |
|--------------------|--------------------------|-------------|
| employee           | id                       | string      |
|                    | age_group                | categorical |
|                    | zip_code                 | int         |
|                    | student                  | bool        |
|                    | german_speaking          | bool        |
|                    | drivers_license          | bool        |
|                    | max_h_per_week           | int         |
|                    | available_from_date      | date        |
|                    | registration             | timestamp   |
| job                | id                       | string      |
|                    | title                    | string      |
|                    | description              | string      |
|                    | zip_code                 | int         |
|                    | initial_demand_qty       | int         |
|                    | current_demand_qty       | int         |
|                    | salary_per_h             | float       |
|                    | start_date               | date        |
|                    | hours_per_week           | int         |
|                    | german_required          | bool        |
|                    | drivers_license_required | bool        |
|                    | timestamp_posting        | timestamp   |
| skills_employee    | skill_1_title            | string      |
|                    | skill_1_description      | string      |
|                    | skill_2_title            | string      |
|                    | skill_2_description      | string      |
|                    | skill_3_title            | string      |
|                    | skill_3_description      | string      |
| skills_job         | skill_1_title            | string      |
|                    | skill_1_description      | string      |
|                    | skill_2_title            | string      |
|                    | skill_2_description      | string      |
|                    | skill_3_title            | string      |
|                    | skill_3_description      | string      |
| job_recommendation | employee_id              | string      |
|                    | job_id                   | string      |
|                    | match_score              | float       |
|                    | explanation              | string      |
|                    | timestamp_recommendation | timestamp   |
| process_status     | process_id               | string      |
|                    | employee_id              | string      |
|                    | job_id                   | string      |
|                    | status_category          | categorical |
|                    | status_timestamp         | timestamp   |

**Comment by lschlesinger** [comment]
Mapping job-skills, employee-skills
- employee
- employee_skills {id, employee_id, title: str, desc: str}
- job
- job_skills {id, job_id, title: str, desc:str}

See #13 for more types

**Comment by floro91** [comment]
table | column | dtype | Priority | comment
-- | -- | -- | -- | --
employee | id | string | 1 |  
  | age_group | categorical | 1 |  
  | zip_code | int | 1 |  
  | student | bool | 1 |  
  | german_speaking | bool | 1 |  
  | drivers_license | bool | 1 |  
  | max_h_per_week | int | 1 |  
  | available_from_date | date | 1 |  
  | registration | timestamp | 1 |  
employer | id | string | 1 |  
  | name | string | 1 |  
  | domain | string | 1 | Could also be categorical?
  | website | string | 1 |  
job | id | string | 1 |  
  | employer_id | string | 1 |  
  | title | string | 1 |  
  | description | string | 1 |  
  | zip_code | int | 1 |  
  | initial_demand_qty | int | 1 |  
  | current_demand_qty | int | 1 | counter to see current qty
  | salary_per_h | float | 1 |  
  | start_date | date | 1 |  
  | hours_per_week | int | 1 |  
  | german_required | bool | 1 |  
  | drivers_license_required | bool | 1 |  
  | timestamp_posting | timestamp | 1 |  
  | welcome_info | string | 1 |  
skills_employee | employee_id | string | 2 |  
  | skill_title | string | 2 |  
  | skill_description | string | 2 |  
skills_job | job_id | string | 2 |  
  | skill_title | string | 2 |  
  | skill_description | string | 2 |  
job_recommendation | employee_id | string | 1 |  
  | job_id | string | 1 |  
  | match_score | float | 1 |  
  | explanation | string | 2 |  
  | timestamp_recommendation | timestamp | 1 |  
contract_status | employee_id | string | 2 |  
  | job_id | string | 2 |  
  | contract_creation | timestamp | 2 |  
  | contract_approved | timestamp | 2 |  
  | contract_signed | timestamp | 2 |
