### ISSUE TITLE
Adjust USP of Readme 

### ISSUE THREAD

**Issue by jgoerner** [jgoerner/corona-hackathon#7]
## 📃 Description
> To be able to better understand what an issue is about, one shall provide some further guidance.
This is what the **Description** is about

This issue deals with refining the USP section of the readme.

## 🚧 Definition of Ready
> To be able to parallelise the work, one has to ensure, that the issues are atomic and contain all information that are needed. The **Definition of Ready** is a checklist which has to be completed, before the issues should be worked on.

The issue ...

- [x] ... has an expressive title
- [x] ... has a concise description
- [x] ... has a content label (e.g. `infrastructure`, `frontend`, `backend`, ...)
- [x] ... has a difficulty label (e.g. `easy`, `medium`, `hard`, ...)
- [x] ... is linked to the global task board
- [x] ... has a definition of done

## ✅Definition of Done 
> To be able to objectively judge, whether a task is done or not, certain acceptance criteria have to be defined. This is what the **Definition of Done** is about.

- [x] Include "batteries included" character
- [x] Refine section about Matching Algorithm

**Comment by lschlesinger** [comment]
Dynamically adapted skill registration form when registering as employee based on the analysis of meta skill catalogue (which "super"-skill is currently needed in a certain location, this should be added in the registration mask for employees)
